# Generated by Django 5.2.5 on 2026-09-20 06:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('model', '0020_evidence_reference_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('stored_name', models.CharField(editable=False, max_length=64, unique=True)),
                ('file_format', models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel workbook (.xlsx)'), ('xls', 'Excel 97-2003 (.xls)')], max_length=10)),
                ('size_bytes', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('content', models.BinaryField()),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_sources', to='model.model')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_sources', to='model.proposal')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_sources', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['model', 'imported_at'], name='ingestion_i_model_i_6f0b13_idx')],
            },
        ),
    ]
