# Generated by Django 5.2.5 on 2026-10-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='assisted_tier',
            field=models.CharField(choices=[('basic', 'Basic'), ('enhanced', 'Enhanced')], default='basic', max_length=20),
        ),
    ]
