services:
  db:
    image: postgres:15
    container_name: weave_dev
    env_file:
      - .env.dev
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7
    container_name: weave_redis_dev
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      default:
        aliases:
          - redis

  web:
    container_name: weave_web_dev
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - /c/Users/Leon/Documents/Weave:/app
    env_file:
      - .env.dev
    environment:
      DJANGO_ENV: dev
      PYTHONUNBUFFERED: 1
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped


  # celery_worker:
  #   build:
  #     context: .
  #   command: celery -A weave worker -l info --concurrency=4
  #   volumes:
  #     - /c/Users/Leon/Documents/Weave:/app
  #   env_file:
  #     - .env.dev
  #   environment:
  #     DJANGO_ENV: dev
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     redis:
  #       condition: service_started
  #     web:
  #       condition: service_started
  #   restart: unless-stopped

  # celery_beat:
  #   build:
  #     context: .
  #   command: celery -A weave beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
  #   volumes:
  #     - /c/Users/Leon/Documents/Weave:/app
  #   env_file:
  #     - .env.dev
  #   environment:
  #     DJANGO_ENV: dev
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     redis:
  #       condition: service_started
  #     web:
  #       condition: service_started
  #   restart: unless-stopped

volumes:
  dev-db-data:
