# Generated by Django 5.2.5 on 2026-09-02 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_alter_model_workspace'),
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='workspace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='workspace.workspace'),
        ),
    ]
