# Generated by Django 5.2.5 on 2026-09-06 22:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_alter_model_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='exclusions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='model',
            name='purpose',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='model',
            name='scope',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='AssertionType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('key', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assertion_types', to='model.model')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objects', to='model.model')),
            ],
        ),
        migrations.CreateModel(
            name='Assertion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assertions', to='model.model')),
                ('assertion_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assertions', to='model.assertiontype')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_assertions', to='model.object')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_assertions', to='model.object')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('key', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_types', to='model.model')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='object',
            name='object_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objects', to='model.objecttype'),
        ),
        migrations.CreateModel(
            name='AttributeDefinition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('key', models.SlugField(max_length=100)),
                ('data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number')], default='text', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('required', models.BooleanField(default=False)),
                ('default_value', models.JSONField(blank=True, null=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assertion_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_definitions', to='model.assertiontype')),
                ('object_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attribute_definitions', to='model.objecttype')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssertionTypeRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_min', models.PositiveIntegerField(default=0)),
                ('subject_max', models.PositiveIntegerField(blank=True, null=True)),
                ('object_min', models.PositiveIntegerField(default=0)),
                ('object_max', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assertion_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='model.assertiontype')),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_rules', to='model.objecttype')),
                ('subject_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_rules', to='model.objecttype')),
            ],
        ),
        migrations.AddConstraint(
            model_name='assertiontype',
            constraint=models.UniqueConstraint(fields=('model', 'key'), name='unique_assertion_type_key_per_model'),
        ),
        migrations.AddConstraint(
            model_name='objecttype',
            constraint=models.UniqueConstraint(fields=('model', 'key'), name='unique_object_type_key_per_model'),
        ),
    ]
