# Generated by Django 5.2.5 on 2026-09-06 22:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_model_exclusions_model_purpose_model_scope_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assertiontype',
            name='model',
        ),
        migrations.RemoveField(
            model_name='attributedefinition',
            name='assertion_type',
        ),
        migrations.RemoveField(
            model_name='assertiontyperule',
            name='assertion_type',
        ),
        migrations.RemoveField(
            model_name='assertiontyperule',
            name='object_type',
        ),
        migrations.RemoveField(
            model_name='assertiontyperule',
            name='subject_type',
        ),
        migrations.CreateModel(
            name='RelationshipType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('key', models.SlugField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationship_types', to='model.model')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('valid_from', models.DateTimeField(blank=True, null=True)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relationships', to='model.model')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_relationships', to='model.object')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_relationships', to='model.object')),
                ('relationship_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='relationships', to='model.relationshiptype')),
            ],
        ),
        migrations.AddField(
            model_name='attributedefinition',
            name='relationship_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relationship_definitions', to='model.relationshiptype'),
        ),
        migrations.CreateModel(
            name='RelationshipTypeRule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_min', models.PositiveIntegerField(default=0)),
                ('subject_max', models.PositiveIntegerField(blank=True, null=True)),
                ('object_min', models.PositiveIntegerField(default=0)),
                ('object_max', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='object_rules', to='model.objecttype')),
                ('relationship_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='model.relationshiptype')),
                ('subject_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_rules', to='model.objecttype')),
            ],
        ),
        migrations.DeleteModel(
            name='Assertion',
        ),
        migrations.DeleteModel(
            name='AssertionType',
        ),
        migrations.DeleteModel(
            name='AssertionTypeRule',
        ),
        migrations.AddConstraint(
            model_name='relationshiptype',
            constraint=models.UniqueConstraint(fields=('model', 'key'), name='unique_relationship_type_key_per_model'),
        ),
    ]
