# Generated by Django 5.2.5 on 2026-09-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_remove_assertiontype_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributedefinition',
            name='nullable',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attributedefinition',
            name='data_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'Date & time'), ('choice', 'Choice')], default='text', max_length=20),
        ),
    ]
