# Generated by Django 5.2.5 on 2026-09-07 00:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_attributedefinition_nullable_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationshiptyperule',
            old_name='object_max',
            new_name='object_maximum',
        ),
        migrations.RenameField(
            model_name='relationshiptyperule',
            old_name='object_min',
            new_name='object_minimum',
        ),
        migrations.RenameField(
            model_name='relationshiptyperule',
            old_name='subject_max',
            new_name='subject_maximum',
        ),
        migrations.RenameField(
            model_name='relationshiptyperule',
            old_name='subject_min',
            new_name='subject_minimum',
        ),
        migrations.AddField(
            model_name='relationshiptyperule',
            name='object_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='relationshiptyperule',
            name='subject_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='object',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_objects', to='model.model'),
        ),
        migrations.AlterField(
            model_name='object',
            name='object_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='typed_objects', to='model.objecttype'),
        ),
        migrations.AlterField(
            model_name='relationship',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_relationships', to='model.model'),
        ),
        migrations.AddConstraint(
            model_name='relationshiptyperule',
            constraint=models.UniqueConstraint(fields=('relationship_type', 'subject_type', 'object_type'), name='unique_relationship_type_rule'),
        ),
    ]
