# Generated by Django 5.2.5 on 2026-09-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0007_rename_object_max_relationshiptyperule_object_maximum_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='object',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='relationship',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
