# Generated by Django 5.2.5 on 2026-09-09 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0008_object_is_active_relationship_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='revision',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
