# Generated by Django 5.2.5 on 2026-09-09 00:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0010_proposal_proposalchange'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposalchange',
            name='proposal',
        ),
        migrations.DeleteModel(
            name='Proposal',
        ),
        migrations.DeleteModel(
            name='ProposalChange',
        ),
    ]
