# Generated by Django 5.2.5 on 2026-09-10 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0012_proposal_proposalchange'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='source',
            field=models.CharField(choices=[('user', 'User'), ('ai', 'AI')], default='user', max_length=20),
        ),
        migrations.AddField(
            model_name='proposal',
            name='validation_status',
            field=models.CharField(choices=[('not_validated', 'Not validated'), ('valid', 'Valid'), ('invalid', 'Invalid')], default='not_validated', max_length=20),
        ),
        migrations.AddField(
            model_name='proposalchange',
            name='parent_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposalchange',
            name='parent_type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='proposalchange',
            name='review_status',
            field=models.CharField(choices=[('unreviewed', 'Unreviewed'), ('reviewed', 'Reviewed')], default='unreviewed', max_length=20),
        ),
        migrations.AddField(
            model_name='proposalchange',
            name='source',
            field=models.CharField(choices=[('user', 'User'), ('ai', 'AI')], default='user', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('working', 'Working'), ('proposed', 'Proposed'), ('approved', 'Approved')], default='working', max_length=20),
        ),
    ]
