# Generated by Django 5.2.5 on 2026-09-11 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0013_proposal_source_proposal_validation_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributedefinition',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
