# Generated by Django 5.2.5 on 2026-09-15 08:49

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def _migrate_legacy_status_values(apps, schema_editor):
    """
    Retire the pre-pipeline 'proposed'/'approved' statuses. 'proposed'
    meant "submitted, awaiting processing" -- the closest new
    equivalent is 'queued'. 'approved' was never actually reachable by
    any code path, but map it to 'completed' for safety.
    """
    Proposal = apps.get_model("model", "Proposal")
    Proposal.objects.filter(status="proposed").update(status="queued")
    Proposal.objects.filter(status="approved").update(status="completed")


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0014_attributedefinition_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalSubmissionResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('success', 'Success'), ('validation_failed', 'Validation failed'), ('system_error', 'System error')], max_length=20)),
                ('before_revision', models.PositiveIntegerField(blank=True, null=True)),
                ('after_revision', models.PositiveIntegerField(blank=True, null=True)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalValidationError',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning')], default='error', max_length=20)),
                ('target_type', models.CharField(blank=True, max_length=50)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('field', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(
            _migrate_legacy_status_values,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='approved_at',
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('working', 'Working'), ('queued', 'Queued'), ('processing', 'Processing'), ('failed', 'Failed'), ('completed', 'Completed')], default='working', max_length=20),
        ),
        migrations.AddIndex(
            model_name='proposal',
            index=models.Index(fields=['model', 'status'], name='model_propo_model_i_b6840d_idx'),
        ),
        migrations.AddField(
            model_name='proposalsubmissionresult',
            name='proposal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission_result', to='model.proposal'),
        ),
        migrations.AddField(
            model_name='proposalvalidationerror',
            name='change',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validation_errors', to='model.proposalchange'),
        ),
        migrations.AddField(
            model_name='proposalvalidationerror',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='model.proposalsubmissionresult'),
        ),
    ]
