# Generated by Django 5.2.5 on 2026-09-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0015_proposalsubmissionresult_proposalvalidationerror_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='acknowledged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
