# Generated by Django 5.2.5 on 2026-09-16 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0016_proposal_acknowledged_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationshiptyperule',
            name='object_required',
        ),
        migrations.RemoveField(
            model_name='relationshiptyperule',
            name='subject_required',
        ),
    ]
