# Generated by Django 5.2.5 on 2026-09-18 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0017_remove_relationshiptyperule_object_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='appearance',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
