# Generated by Django 5.2.5 on 2026-09-19 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0018_model_appearance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributedefinition',
            name='data_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'Date & time'), ('choice', 'Choice'), ('url', 'URL')], default='text', max_length=20),
        ),
    ]
