# Generated by Django 5.2.5 on 2026-09-19 23:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


def backfill_completed_at(apps, schema_editor):
    """
    Proposals committed before completed_at existed: the submission result
    was last written when the commit landed, so use that, falling back to the
    proposal's own updated_at.
    """

    Proposal = apps.get_model("model", "Proposal")
    ProposalSubmissionResult = apps.get_model("model", "ProposalSubmissionResult")

    committed_at = dict(
        ProposalSubmissionResult.objects.filter(outcome="success").values_list(
            "proposal_id", "updated_at"
        )
    )

    for proposal in Proposal.objects.filter(status="completed", completed_at__isnull=True):
        Proposal.objects.filter(pk=proposal.pk).update(
            completed_at=committed_at.get(proposal.pk, proposal.updated_at)
        )


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0019_alter_attributedefinition_data_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceReference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(max_length=500)),
                ('locator', models.CharField(blank=True, max_length=500)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddField(
            model_name='proposal',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.RunPython(backfill_completed_at, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='proposal',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Change note'),
        ),
        migrations.AddIndex(
            model_name='proposalchange',
            index=models.Index(fields=['target_id', 'target_type'], name='model_propo_target__488d32_idx'),
        ),
        migrations.AddField(
            model_name='evidencereference',
            name='change',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='model.proposalchange'),
        ),
    ]
