# Generated by Django 5.2.5 on 2026-09-28 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0020_evidence_reference_completed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='revision',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
