/**
 * Golden parity: the JS Explorer engine must produce exactly what the Python
 * Explorer produced for the same dataset and state.
 *
 * The fixture is generated by ``publication/tests/test_parity.py`` from the
 * Python implementation; this test replays it through the JS engine.
 */

import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import test from "node:test";

import { createDataset } from "../../model/static/model/js/explore/engine/dataset.js";
import { objectDetails, relationshipDetails } from "../../model/static/model/js/explore/engine/details.js";
import { compileGraph } from "../../model/static/model/js/explore/engine/graph.js";
import { project } from "../../model/static/model/js/explore/engine/projection.js";
import { sanitiseState, toState } from "../../model/static/model/js/explore/engine/query.js";
import { searchObjects } from "../../model/static/model/js/explore/engine/search.js";

const fixture = JSON.parse(readFileSync(new URL("./fixtures/parity.json", import.meta.url), "utf8"));

const contractual = (dropped) => dropped.map(({ kind, reason }) => ({ kind, reason }));

for (const testCase of fixture.cases) {
  const dataset = createDataset(testCase.dataset);

  testCase.steps.forEach((step, index) => {
    const label = `${testCase.name} #${index} ${JSON.stringify(step.state).slice(0, 90)}`;
    const { query, dropped } = sanitiseState(step.state, dataset);
    const projection = project(dataset, query);

    test(`graph parity: ${label}`, () => {
      assert.deepEqual(toState(query), step.graph.state);
      assert.deepEqual(contractual(dropped), step.graph.dropped);
      assert.deepEqual(projection.summary, step.graph.summary);
      assert.deepEqual(compileGraph(dataset, projection, testCase.template), step.graph.payload);
    });

    for (const search of step.search ?? []) {
      test(`search parity: ${testCase.name} #${index} q=${JSON.stringify(search.q)}`, () => {
        const actual = { ...searchObjects(dataset, search.q, { projection }), state: toState(query) };
        assert.deepEqual(actual, search.result);
      });
    }

    if (step.details) {
      test(`details parity: ${label}`, () => {
        for (const [id, expected] of Object.entries(step.details.objects)) {
          assert.deepEqual(objectDetails(dataset, id, projection), expected, `object ${id}`);
        }
        for (const [id, expected] of Object.entries(step.details.relationships)) {
          assert.deepEqual(relationshipDetails(dataset, id, projection), expected, `relationship ${id}`);
        }
      });
    }
  });
}
