# Generated by Django 5.2.5 on 2026-10-01 21:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai', '0001_initial'),
        ('model', '0021_alter_model_revision'),
        ('workspace', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssistedTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(choices=[('create', 'Create'), ('reconcile', 'Reconcile'), ('change', 'Change'), ('assess', 'Assess')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('ready_for_review', 'Ready for review'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('ai_outcome', models.CharField(blank=True, max_length=30)),
                ('failure_reason_code', models.CharField(blank=True, choices=[('execution_failed', 'Execution failed'), ('unresolved', 'Unresolved'), ('needs_clarification', 'Needs clarification'), ('no_change_produced', 'No change produced'), ('proposal_abandoned', 'Proposal abandoned'), ('stale_timed_out', 'Stale / timed out')], max_length=30)),
                ('failure_reason', models.TextField(blank=True)),
                ('refinement_cycles', models.PositiveIntegerField(default=0)),
                ('context_expansions', models.PositiveIntegerField(default=0)),
                ('submitted_intent', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ready_for_review_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_execution', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_task', to='ai.aiexecution')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assisted_tasks', to=settings.AUTH_USER_MODEL)),
                ('model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_tasks', to='model.model')),
                ('proposal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assisted_task', to='model.proposal')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assisted_tasks', to='workspace.workspace')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AssistedTaskEvidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_filename', models.CharField(max_length=255)),
                ('content_type', models.CharField(blank=True, max_length=100)),
                ('size_bytes', models.PositiveIntegerField()),
                ('sha256', models.CharField(max_length=64)),
                ('content', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='assisted.assistedtask')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='assistedtask',
            index=models.Index(fields=['workspace', 'status'], name='assisted_as_workspa_f184df_idx'),
        ),
        migrations.AddIndex(
            model_name='assistedtask',
            index=models.Index(fields=['model', 'status'], name='assisted_as_model_i_305ea5_idx'),
        ),
        migrations.AddConstraint(
            model_name='assistedtask',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['queued', 'running', 'ready_for_review'])), fields=('model',), name='unique_active_assisted_task_per_model'),
        ),
    ]
