# Generated by Django 5.2.5 on 2026-10-02 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assisted', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assistedtask',
            name='failure_reason_code',
            field=models.CharField(blank=True, choices=[('execution_failed', 'Execution failed'), ('unresolved', 'Unresolved'), ('needs_clarification', 'Needs clarification'), ('no_change_produced', 'No change produced'), ('proposal_abandoned', 'Proposal abandoned'), ('stale_timed_out', 'Stale / timed out'), ('entitlement_denied', 'Entitlement denied')], max_length=30),
        ),
    ]
