# Generated by Django 5.2.5 on 2026-10-05 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assisted', '0003_assistedtask_tokens_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistedtask',
            name='outcome_detail',
            field=models.TextField(blank=True),
        ),
    ]
