# Generated by Django 5.2.5 on 2026-10-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assisted', '0004_assistedtask_outcome_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='assistedtask',
            name='current_stage',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='assistedtask',
            name='findings',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='assistedtask',
            name='provider_calls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assistedtask',
            name='stage_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
