# Generated by Django 5.2.5 on 2026-09-20 02:54

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('model', '0020_evidence_reference_completed_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('source_revision', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('filename', models.CharField(max_length=120)),
                ('scope', models.JSONField(default=dict)),
                ('presentation', models.JSONField(default=dict)),
                ('default_view', models.JSONField(default=dict)),
                ('appearance_snapshot', models.JSONField(default=dict)),
                ('object_count', models.PositiveIntegerField(default=0)),
                ('relationship_count', models.PositiveIntegerField(default=0)),
                ('content_digest', models.CharField(max_length=64)),
                ('format_version', models.PositiveSmallIntegerField(default=1)),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='model.model')),
                ('published_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='publications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sequence'],
                'indexes': [models.Index(fields=['model', '-sequence'], name='publication_model_seq_idx')],
                'constraints': [models.UniqueConstraint(fields=('model', 'sequence'), name='unique_publication_sequence_per_model')],
            },
        ),
    ]
