# Generated by Django 5.2.5 on 2026-09-30 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='bundle',
            field=models.JSONField(default=dict),
        ),
    ]
