# Generated by Django 5.2.5 on 2026-10-01 05:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('model', '0021_alter_model_revision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIExecution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(max_length=50)),
                ('execution_status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='running', max_length=20)),
                ('outcome', models.CharField(blank=True, choices=[('ready_for_review', 'Ready for review'), ('no_change_required', 'No change required'), ('needs_user_clarification', 'Needs user clarification'), ('unresolved', 'Unresolved'), ('failed', 'Failed')], max_length=30, null=True)),
                ('provider', models.CharField(default='openai', max_length=50)),
                ('provider_model', models.CharField(blank=True, max_length=100)),
                ('refinement_cycles', models.PositiveIntegerField(default=0)),
                ('context_expansions', models.PositiveIntegerField(default=0)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('context_digest', models.CharField(blank=True, max_length=64)),
                ('result_digest', models.CharField(blank=True, max_length=64)),
                ('error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_executions', to='model.model')),
                ('proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_executions', to='model.proposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ai_executions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
