# Generated by Django 5.2.5 on 2026-10-06 08:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiexecution',
            name='provider_calls',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='aiexecution',
            name='stage_summary',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name='AIExecutionStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('call_index', models.PositiveIntegerField()),
                ('stage', models.CharField(max_length=30)),
                ('stage_attempt', models.PositiveIntegerField(default=1)),
                ('decision', models.CharField(max_length=30)),
                ('issue_codes', models.JSONField(blank=True, default=dict)),
                ('verdict', models.CharField(blank=True, max_length=30)),
                ('usage', models.JSONField(blank=True, default=dict)),
                ('input_digest', models.CharField(blank=True, max_length=64)),
                ('output_digest', models.CharField(blank=True, max_length=64)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='ai.aiexecution')),
            ],
            options={
                'ordering': ['execution', 'call_index'],
            },
        ),
    ]
